name = "MBSinBLG"
uuid = "ed60015f-8074-49d8-9504-349d4a9968de"
authors = ["Fernando Peñaranda"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
